### ISSUE TITLE
Video Load Failed

### ISSUE THREAD

**Issue by gbest7** [tgdrive/teldrive#358]
Server Version: 1.5.1

'Video Load Failed' after 5 reconnects trying to play from teldrive web.

These files worked fine, but are now giving me errors in recent versions

**Comment by vavtnen** [comment]
This happens to me also. Most files refuse to play even downloaded. If they do play they play up to the 1st chunk size which is 500mb in my case. Go back to 1.4.20 will play all files, but I am unable to add new file since started column was removed.

I am trying to figure out how to roll back teldrive.files table so I can use it with 1.4.20

**Comment by SingingDalong** [comment]
DB backup is required before updating teldrive.

**Comment by xd003** [comment]
I also faced this issue. It's working fine in mount but nothing would play or download from teldrive Web UI. I didn't found any error as such in teldrive logs.

**Comment by ypitalia** [comment]
Same for my 1.5.3. 'Video Load Failed' after 5 reconnects and not possible to download (also rcloud and rcloud mount) files, before were ok (same version, and formers)
